spring:

  docker:
    compose:
      file: src/main/docker/compose.yaml
      enabled: true
      lifecycle-management: start_only

  jpa:
    properties:
      hibernate:
        default_schema: public


  liquibase:
    change-log: db/changelog/master.yaml

server:
  port: 8443
  ssl:
    key-alias: baeldung
    key-store: classpath:keystore.p12
    key-store-password: changeit
    key-store-type: PKCS12
    key-password: changeit

